- hosts: all
  become: yes
  tasks: 
    - name: "Install Apache"
      yum: 
          name: httpd
          state: installed
          update_cache: true
      notify: 
          - Start httpd

    - name: "Download webcontent"
      unarchive: 
          src: https://files.mmce.me/MSc/ansibleLab.zip
          dest: /var/www/html/
          remote_src: True

    - name: "Upgrade all packages"
      yum:
        name: '*'
        state: latest

  handlers: 
    - name: Start httpd
      service: 
          name: httpd
          state: started
